spring:
  datasource:
<<<<<<< HEAD
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://121.4.112.204:3306/bmc_erp?Unicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
     username: root
     password: 123!@#jklJKL
=======
<<<<<<< HEAD
    name: springboot
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filter: stat,wall
      #mysql驱动
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://121.4.112.204:3306/bmc_erp?Unicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123!@#jklJKL
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      stat-view-servlet:
        login-username: admin
        login-password: admin
>>>>>>> 9f452c535cbd220d0c4163fcdc9e8f98a24b9d31
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: none
        show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB