//公共
export const COM_PROVINCE_LIST = 'COM_PROVINCE_LIST'
export const COM_CITY_LIST = 'COM_CITY_LIST'
export const COM_AREA_LIST = 'COM_AREA_LIST'
export const COM_COMPANY_INFO = 'COM_COMPANY_INFO'
export const COM_TAX_RATE_LIST = 'COM_TAX_RATE_LIST'

//login
export const LOGIN_USERINFO = 'LOGIN_USERINFO'
export const USER_VO_LIST = 'USER_VO_LIST'

//contract
export const CONTRACT_TEMPLATE = 'CONTRACT_TEMPLATE'
export const CUSTOMER_VO_LIST = 'CUSTOMER_VO_LIST'
export const CONTRACT_INTENTION_LIST = 'CONTRACT_INTENTION_LIST'
export const CONTRACT_FORMAL_LIST = 'CONTRACT_FORMAL_LIST'

//order
export const CREATED_ORDER="CREATED_ORDER"
export const ORDER_DETAIL_LIST="ORDER_DETAIL_LIST"
export const ORDER_STATE_SUMMARY="ORDER_STATE_SUMMARY"
export const ORDER_PRODUCE_TYPE_SUMMARY="ORDER_PRODUCE_TYPE_SUMMARY"
export const ORDER_FORM_PROCESS_LIST="ORDER_FORM_PROCESS_LIST"


//produceSetting
export const PRODUCE_PROCESS_LIST="PRODUCE_PROCESS_LIST"
export const PRODUCE_LINE_LIST="PRODUCE_LINE_LIST"
export const DELETE_PRODUCE_PROCESS="DELETE_PRODUCE_PROCESS"
export const DELETE_PRODUCE_LINE="DELETE_PRODUCE_LINE"

//produce plan
export const PRODUCE_PLAN_LIST="PRODUCE_PLAN_LIST"
export const PRODUCE_PLAN_RECORD_LIST="PRODUCE_PLAN_RECORD_LIST"

//produce monitor
export const PRODUCE_LINE_STATE_LIST="PRODUCE_LINE_STATE_LIST"
export const PROCESSING_PLAN__LIST="PROCESSING_PLAN__LIST"
export const PRODUCE_PLAN_COUNT_SUMMARY="PRODUCE_PLAN_COUNT_SUMMARY"

//delegate
export const DELEGATE_RELEASE_LIST="DELEGATE_RELEASE_LIST"
export const DELEGATE_PROCESSING_LIST="DELEGATE_PROCESSING_LIST"
export const DELEGATE_RECORD_LIST="DELEGATE_RECORD_LIST"

//storage
export const STORAGE_DETAIL_LIST="STORAGE_DETAIL_LIST"




//purchase
export const PURCHASE_DETAIL_LIST="PURCHASE_DETAIL_LIST"
export const PURCHASE_PUSH_LIST="PURCHASE_PUSH_LIST"
export const PRODUCT_VO_LIST = 'PRODUCT_VO_LIST'
export const PURCHASE_DELETE_ITEM="PURCHASE_DELETE_ITEM"
export const PURCHASE_WAIT_LIST="PURCHASE_WAIT_LIST"
export const PURCHASE_REJECT_ITEM="PURCHASE_REJECT_ITEM"
export const PO_WAIT_LIST="PO_WAIT_LIST"
export const PO_CREATE_LIST="PO_CREATE_LIST"
export const ALL_PRD_LIST="ALL_PRD_LIST"
export const ALL_POD_LIST="ALL_POD_LIST"
export const PR_BUYING_LIST="PR_BUYING_LIST"
export const PR_SUMMARY_LIST="PR_SUMMARY_LIST"
export const PR_SUMMARYDASHBOARD_LIST="PR_SUMMARYDASHBOARD_LIST"