//公共
export const COM_PROVINCE_LIST = 'COM_PROVINCE_LIST'
export const COM_CITY_LIST = 'COM_CITY_LIST'
export const COM_AREA_LIST = 'COM_AREA_LIST'

//login
export const LOGIN_USERINFO = 'LOGIN_USERINFO'

//contract
export const CONTRACT_TEMPLATE = 'CONTRACT_TEMPLATE'
export const CUSTOMER_VO_LIST = 'CUSTOMER_VO_LIST'
export const CONTRACT_INTENTION_LIST = 'CONTRACT_INTENTION_LIST'
export const CONTRACT_FORMAL_LIST = 'CONTRACT_FORMAL_LIST'

//order
export const CREATED_ORDER="CREATED_ORDER"
export const ORDER_DETAIL_LIST="ORDER_DETAIL_LIST"


